// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-GcBS4V7VDyO2pliK9xhAxzCcGqMGzAY',
    appId: '1:1051579869558:web:9a1f73d1592d24110b7257',
    messagingSenderId: '1051579869558',
    projectId: 'jam3eya-1407d',
    authDomain: 'jam3eya-1407d.firebaseapp.com',
    storageBucket: 'jam3eya-1407d.firebasestorage.app',
    measurementId: 'G-N7MJ7TY27Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMTr5b8nMGnW0AqLDNhAg9ZOw5k84fPyU',
    appId: '1:1051579869558:android:d43344b660d1d2520b7257',
    messagingSenderId: '1051579869558',
    projectId: 'jam3eya-1407d',
    storageBucket: 'jam3eya-1407d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAPQ1PXLUPLVta8PobikYMVtVTqiTyVEw',
    appId: '1:1051579869558:ios:18fc3fd54780796c0b7257',
    messagingSenderId: '1051579869558',
    projectId: 'jam3eya-1407d',
    storageBucket: 'jam3eya-1407d.firebasestorage.app',
    iosBundleId: 'com.example.jam3eya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAPQ1PXLUPLVta8PobikYMVtVTqiTyVEw',
    appId: '1:1051579869558:ios:18fc3fd54780796c0b7257',
    messagingSenderId: '1051579869558',
    projectId: 'jam3eya-1407d',
    storageBucket: 'jam3eya-1407d.firebasestorage.app',
    iosBundleId: 'com.example.jam3eya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-GcBS4V7VDyO2pliK9xhAxzCcGqMGzAY',
    appId: '1:1051579869558:web:0c73eb6cd7930ef70b7257',
    messagingSenderId: '1051579869558',
    projectId: 'jam3eya-1407d',
    authDomain: 'jam3eya-1407d.firebaseapp.com',
    storageBucket: 'jam3eya-1407d.firebasestorage.app',
    measurementId: 'G-BZG420YH0K',
  );
}
